INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234', now());
INSERT INTO TB_TECNICO (nome, telefone, email, senha, created_at) VALUES ('Marcos Rogerio', '86876876', 'marcos@gmail.com', '1234', now());
INSERT INTO TB_SETOR (coordenador, email, nome, sigla, telefone, created_at) VALUES ('Matheus', 'matheus@gmail.com', 'Direcao Geral', 'DIRGE', '3461-0000', now());
INSERT INTO TB_SETOR (coordenador, email, nome, sigla, telefone, created_at) VALUES ('Gustavo', 'gustavo@gmail.com', 'Servico de Tecnologia da Informacao e Suporte Tecnico', 'SERTI', '34615952', now());
INSERT INTO TB_SETOR (coordenador, email, nome, sigla, telefone, created_at) VALUES ('Jose', 'josesilva@gmail.com', 'Coordenacao de Materiais', 'COMAT', '34614561', now());
INSERT INTO TB_SETOR (coordenador, email, nome, sigla, telefone, created_at) VALUES ('Felipe', 'felipegomes@gmail.com', 'Coordenacao de Administracao da Sede', 'COADS', '34613461', now());
INSERT INTO TB_SETOR (coordenador, email, nome, sigla, telefone, created_at) VALUES ('Matias', 'matias_felipe@gmail.com', 'Nucleo de Gestao Administrativa e Educacional', 'NUGED', '34611643', now());
INSERT INTO TB_SETOR (coordenador, email, nome, sigla, telefone, created_at) VALUES ('Fernanda', 'fernadahta@gmail.com', 'Coordenacao de Gestao Academica', 'COGEA', '34613333', now());
INSERT INTO TB_SETOR (coordenador, email, nome, sigla, telefone, created_at) VALUES ('Andre', 'andre_souza1444@gmail.com', 'Diretoria de Administracao', 'DIRAD', '34619410', now());
INSERT INTO TB_SETOR (coordenador, email, nome, sigla, telefone, created_at) VALUES ('Gabriela', 'gabi_hta-444@gmail.com', 'Coordenacao de Gestao de Pessoas', 'COGEP', '34616315', now());
INSERT INTO TB_SETOR (coordenador, email, nome, sigla, telefone, created_at) VALUES ('Fabiola', 'fabiola984@gmail.com', 'Coordenacao de Planejamento e Orcamento', 'COPOR', '34610144', now());
INSERT INTO TB_SETOR (coordenador, email, nome, sigla, telefone, created_at) VALUES ('Gabriel', 'gabriel_molina@gmail.com', 'Direcao Geral', 'DIRGE', '34614154', now());